### ISSUE TITLE
Export by Collection includes entire storage folder

### ISSUE THREAD

**Issue by cculbreath** [plandes/zotsite#6]
When exporting by collection, I think it would make sense for the script to check against the actual files being referenced in that collection instead of copying the entire storage folder. I have well over 1GB in my library, but want to create a website for a small subset.

**Comment by plandes** [comment]
@cculbreath  I just recently closed an issue of someone else wanting this feature.  I've thought about adding it myself just for others, but after looking into I discovered it was more work than expected.  Would you be interested in adding this feature and submitting a pull request?

If there are enough people that want it, I'll add it and this time I'll leave this issue open until someone (including myself if it happens) adds the feature.

**Comment by plandes** [comment]
This functionality has been added to version [0.3.0](https://github.com/plandes/zotsite/blob/master/CHANGELOG.md).   See the [documentation](https://github.com/plandes/zotsite#subcollections) on exporting sub collections.

**Comment by floriandierickx** [comment]
Thank you for this interesting tool! I came across this question in search for a possibility to make a website of a subset of collection(s) of Zotero (as I have a really large library, this feature is quite essential not to double my disk space size :p)

Following the guidelines in https://plandes.github.io/zotsite/doc/usage.html#subcollections, I tried creating a website of the collection(s) ![image](https://github.com/plandes/zotsite/assets/12695083/24d24eb1-595a-46a4-ae61-126f50c5180c) using the following commands:
```
zotsite export --collection '.*CC\s*Impacts.*'
zotsite export --collection '.*CC\sImpacts.*'
zotsite export --collection '.*CC\sImpacts'
zotsite export --collection 'CC\sImpacts'
```
The command succesfully generates the following cues:
```
zotsite: exporting site: None
zotsite: copying static data -> zotero-site
zotsite: creating js nav tree: zotero-site\js\zotero-tree-data.js
zotsite: reading SQLite file: C:\Users\dxf\Zotero\zotero.sqlite
Usage: zotsite [options]
```
But the final line is always `zotsite: error: no collections found; maybe too restrictive collections regular expression?`

The result is a generated website in the subfolder `zotero-site` that remains empty.

Do you/somebody know what I might be doing wrong?

As a side-question: does this feature also export the sub-collections (hierarchically?) to the generated website?

![image](https://github.com/plandes/zotsite/assets/12695083/24d24eb1-595a-46a4-ae61-126f50c5180c)

**Comment by plandes** [comment]
Hi @floriandierickx 
This error means that there's a file it cannot copy, and the file looks bogus (the trailing `false` file name).  It's hard from just this to debug it and I cannot reproduce this error (export works for me using a similar regular expression).

Do I understand correctly that you're able to export, but the regular expression you're using produces the error?  What specifically produces this error?

Re Windows: I do not use Windows myself, but IIRC, others do and all the file system access uses APIs that abstract it away so that shouldn't be the issue?

What files are in `C:\Users\USER\\Zotero\storage\9QFSS3TC` directory?  Also can you confirm it is a directory?

Please add the `--level debug` to the command line and run it exactly how you did before. Then provide that output.

**Comment by plandes** [comment]
@floriandierickx Also, please create a new issue and refer to it here.  This is not at all related to the issue in this thread.

Thank you.

**Comment by floriandierickx** [comment]
hey @plandes, thank you for the clarifications! I initially planned to just share my enthusiasm for this feature in a short note, but on the way that short note became indeed a new issue. I have rephrased the issue with more details in #26.
